// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD17SynKIO8DGlJTtPNMAHvgP55KQh_BYc',
    appId: '1:461626509183:web:efe39b73a560efe8f07c4a',
    messagingSenderId: '461626509183',
    projectId: 'chat-15496',
    authDomain: 'chat-15496.firebaseapp.com',
    databaseURL: 'https://chat-15496-default-rtdb.firebaseio.com',
    storageBucket: 'chat-15496.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDf4eC5DeQXvRmtnHvcx8vfdI3vdJDHr2I',
    appId: '1:461626509183:android:23afc139559902a7f07c4a',
    messagingSenderId: '461626509183',
    projectId: 'chat-15496',
    databaseURL: 'https://chat-15496-default-rtdb.firebaseio.com',
    storageBucket: 'chat-15496.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRnwH6czdB48knV14Jvna-xyf6ANMOybc',
    appId: '1:461626509183:ios:b9a64ff287011b4df07c4a',
    messagingSenderId: '461626509183',
    projectId: 'chat-15496',
    databaseURL: 'https://chat-15496-default-rtdb.firebaseio.com',
    storageBucket: 'chat-15496.appspot.com',
    iosClientId: '461626509183-ncs0iragv57dhdc6nla5ev1gdv7amja6.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRnwH6czdB48knV14Jvna-xyf6ANMOybc',
    appId: '1:461626509183:ios:999ca94e5aa86d34f07c4a',
    messagingSenderId: '461626509183',
    projectId: 'chat-15496',
    databaseURL: 'https://chat-15496-default-rtdb.firebaseio.com',
    storageBucket: 'chat-15496.appspot.com',
    iosClientId: '461626509183-6m1vnpbahgo7u071hboavevltmc0hsp2.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat.RunnerTests',
  );
}
